Fix backen not found in director
ysugimoto/falco pull request #208
Opened 2023-11-13 19:38 UTC by MasonM

This should fix https://github.com/ysugimoto/falco/issues/196, or at least one of the causes of these errors. The problem is that `ProcessDeclarations()` method parses the declarations in order, and if a `director` declaration references a `backend` declaration that's defined later, it'll trigger `backend 'F_Custom_backend' is not found`. The fix is to have `ProcessDeclarations()` do two passes: the first to process backends and the second for everything else.

2023-11-21 10:39 UTC, ysugimoto requested changes
Thanks, I realized that this is a backend hoisting problem 👍 
And I put one suggestion about keeping less complexity.

2023-11-21 10:39 UTC, ysugimoto commented on interpreter/interpreter.go
> +	}
![Suggestion](https://img.shields.io/badge/review-suggestion-red)
Could you define this loop as a separated function like `ProcessBackends()` ? it makes be less complex I think.

2023-11-21 16:32 UTC, MasonM commented
Sure thing. I'm on vacation right now, but I'll do this when I get back on
Friday.

On Tue, Nov 21, 2023, 5:39 AM Yoshiaki Sugimoto ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks, I realized that this is a backend hoisting problem 👍
> And I put one suggestion about keeping less complexity.
> ------------------------------
>
> In interpreter/interpreter.go
> <https://github.com/ysugimoto/falco/pull/208#discussion_r1400371202>:
>
> >  	for _, stmt := range statements {
> -		// Call debugger
> +		t, ok := stmt.(*ast.BackendDeclaration)
> +		if !ok {
> +			continue
> +		}
>  		i.Debugger.Run(stmt)
> +		h := &atomic.Bool{}
> +		h.Store(true)
> +		// Determine default backend
> +		if i.ctx.Backend == nil {
> +			i.ctx.Backend = &value.Backend{Value: t, Literal: true, Healthy: h}
> +		}
> +		if _, ok := i.ctx.Backends[t.Name.Value]; ok {
> +			return exception.Runtime(&t.Token, "Backend %s is duplicated", t.Name.Value)
> +		}
> +		i.ctx.Backends[t.Name.Value] = &value.Backend{Value: t, Literal: true, Healthy: h}
> +	}
>
> [image: Suggestion]
> <https://camo.githubusercontent.com/dfa08c603dcb60487c25ac0b3cd09b03f592f2032fc8c6a05002641d0f91ac98/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f7265766965772d73756767657374696f6e2d726564>
> Could you define this loop as a separated function like ProcessBackends()
> ? it makes be less complex I think.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ysugimoto/falco/pull/208#pullrequestreview-1741658231>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAE67WDEMXE56KNQPZJAZF3YFSAGBAVCNFSM6AAAAAA7JVKSSSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONBRGY2TQMRTGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-25 02:04 UTC, MasonM commented
Okay, I pushed a commit to extract the logic to a `ProcessBackends()` function and added some additional tests

2023-11-25 08:30 UTC, ysugimoto approved these changes
Looks good, thanks!

2023-11-25 14:14 UTC, merged