Add feature to collect function/statement/branch coverage to `test` command
ysugimoto/falco pull request #343
Opened 2024-07-28 11:05 UTC by nodaguti

This PR implements a new feature to collect test coverage data while running tests with `-c` / `--coverage` option enabled and report them in the output (either in human-friendly way or in JSON).

Approach
---
There are roughly two ways to implement coverage measurement: 1) collecting coverage in the interpreter side (like [V8 JavaScript code coverage](https://v8.dev/blog/javascript-code-coverage)), and 2) collecting coverage in the VCL side (like [Istanbul test coverage](https://istanbul.js.org/))

For option 1, adding support for code coverage to our interpreter may result in tight coupling between the interpreter and coverage measurement, which I think would not a great idea especially when considering a fact that falco uses the interpreter not only in tester but also in simulator and console features.

For option 2, since we already have a special function to mutate an existing table in tester mode, `testing.table_set`, tables can be used to store coverage data.

This PR adds a new process called "intstrumentation" to the preparation phase of testing: traversing an AST tree to find subroutines, statements, and branches to initialise coverage tables, and injecting `testing.table_set` statements to record executions of each subroutine, statement, or branch.

These injected statements will be evaluated along with original VCL code and produce coverage information for each test case.

After running all tests, each coverage information will be merged so that falco can calculate overall coverage percentages.

Screenshot
---
<img width="545" alt="Screenshot 2024-07-21 at 4 08 02 PM" src="https://github.com/user-attachments/assets/b30bd437-5f8c-4464-9f35-19c97651bb3f">

Related Issues
---
- https://github.com/ysugimoto/falco/issues/314

2024-07-28 11:06 UTC, nodaguti commented
@ysugimoto 
I'm sorry for the PR being relatively large, but I look forward to hearing your impressions. Thank you!

2024-07-30 07:40 UTC, ysugimoto requested changes
This PR seems to be conceptual and looks very cool approach.

I put some request changes for adjusting current implementation, and this will be needed more working so could you change the base branch to the `develop`?
I've just created `develop` branch from current `main` branch, let's do more working on it.

2024-07-30 07:40 UTC, ysugimoto commented on interpreter/coverage.go
> +				Token: token.Token{Type: token.STRING, Literal: "testing.table_set"},
I suggest that you can create new testing function for marking converage like `coverage.mark()` but it's okay for this PR. we can do it later!

2024-07-30 07:40 UTC, ysugimoto commented on interpreter/coverage_test.go
> +}
This looks tricky a bit but very interesting, awesome!

2024-07-30 07:40 UTC, ysugimoto commented on interpreter/testing.go
> +func (i *Interpreter) TestProcessInit(r *http.Request, c *config.TestConfig) error {
Passing a bool argument like `enableCoverage bool` seems to be enough.

2025-01-28 10:36 UTC, ysugimoto commented
@nodaguti Will you continue to work on this PR?
I think basically Okay so will merge into `main` and refactor it on an another PR.

2025-02-24 15:47 UTC, ysugimoto commented
Close with #414, thanks for great conceptual work.

2025-02-24 15:47 UTC, closed without merging