Allow req.backend to be read as a string
ysugimoto/falco pull request #96
Opened 2022-08-22 16:29 UTC by ivomurrell

Fastly [documents](https://developer.fastly.com/reference/vcl/variables/backend-connection/req-backend/) some curious behaviour for the `req.backend` variable:

> Upon reading in a [STRING](https://developer.fastly.com/reference/vcl/types/string/) context, `req.backend` is converted to a [STRING](https://developer.fastly.com/reference/vcl/types/string/) and prepended with the backend's `share_key` property, which is your service ID (for backends created via the API, CLI, or web interface), the string "fastlyshield" (for [shield](https://developer.fastly.com/learning/concepts/shielding) backends), or whatever you defined (for backends [defined in VCL](https://developer.fastly.com/reference/vcl/declarations/backend/)).

So `req.backend` is typically a `BACKEND` but it can be cast to a `STRING` as well, unlike other `BACKEND` values! We make use of this behaviour in our code to track what backend has been used for debugging purposes, i.e.:
```vcl
set resp.http.Debug-Fastly-Backend = req.backend;
```
Currently falco (understandably) prints a linter error when encountering this code
```
🔥 [ERROR] resp.http.Debug-Fastly-Backend wants type STRING but assign BACKEND (operator/assignment)
```

I'm honestly not sure what the best workaround for this would be. I think the big question is: do any other Fastly variables exhibit similar magical casting behaviour? If so, it would probably be worth expanding the `predefined.yml` specification to allow `get` and `set` fields to return an array or their different possible types.

For now, however, I'm assuming (or hoping) that this isn't the case and we can instead construct a specific hack for `req.backend`. I've started this off by adding an additional check in `lintAssignOperator` for whether you're reading the `req.backend` identifier. For this to work consistently we'll need to copy the check to all other places where a value is read, such as in `lintFunctionArguments`.

It's very messy work though and I'm wondering if anyone knows a better way to handle these values which can have multiple types. Is there anything in code already that supports this behaviour?

P.S. Thanks for giving me write access to the repository; I've made this change a branch in the repository rather than our fork!

2022-08-22 17:14 UTC, davinci26 reviewed
Wonder if we could have a property that declares if the value can be implicitly cast to string and `req.backend` or BackendType would set this to true

2022-08-22 18:11 UTC, davinci26 commented
Also a bit orthogonal but we should be adding a warning if someone uses req.backend on `vcl_log` or `vcl_deliver` since it will be `null`  or incorrect. If you dont want to do that now we should open an issue for that so that we dont forget

2022-08-23 14:02 UTC, ysugimoto commented
VCL behaves mysteriously type conversion that the type conversion depends on the right-side member is a variable or literal.
When I started to make `falco`, I investigated type conversion systems of all types [here](https://docs.google.com/spreadsheets/d/16xRPugw9ubKA1nXHIc5ysVZKokLLhysI-jAu3qbOFJ8/edit#gid=0) (hope this helps somewhere) but this lacks BACKEND type 😓 

In my understanding, the backend **variable** will be converted to string but literal will be an error, so,

```vcl
set req.backend = F_origin_0;
set req.http.Debug-Fastly-Backend = req.backend; // Valid

----

set req.http.Debug-Fastly-Backend = F_origin_0; // Invalid, confusing...
```

Then, I agree with @davinci26 , I'm just thinking that we could have an extensible method in `types.Type` (e.g  types.Type.CanConvertTo(types.Type) bool)` and check the type conversion is allowed or not through this method.
Almost VCL type conversion problem may be STRING type (e.g. HTTP Headers) but each types could do so for our future. What do you think about this?

2022-08-26 14:47 UTC, ivomurrell commented
> I'm just thinking that we could have an extensible method in types.Type (e.g types.Type.CanConvertTo(types.Type) bool)` and check the type conversion is allowed or not through this method.

I'm not sure this would work as the `BACKEND` type itself is not convertable to a `STRING` as your table actually shows in [this cell](https://docs.google.com/spreadsheets/d/16xRPugw9ubKA1nXHIc5ysVZKokLLhysI-jAu3qbOFJ8/edit#gid=0&range=G6), but the `req.backend` variable is an exception to the rule. That's why `set req.http.Debug-Fastly-Backend = req.backend;` works but `set req.http.Debug-Fastly-Backend = F_origin_0;` doesn't. So this means that for the returned value of `types.Type.CanConvertTo` to be correct, we'd have to know the name of the identifier (so we can see whether it's `req.backend` or not), which we don't have access to in the `types.Backend` struct.

The 'cleanest' solution might be defining a special `REQBACKEND` type to describe the unique behaviour, but it would probably be simpler and more maintainable to just hack the identifier checks into the linter phase like I started doing 😅 Does that sound acceptable?

2022-08-27 02:24 UTC, ysugimoto commented
> I'm not sure this would work as the BACKEND type itself is not convertable to a STRING as your table actually shows in [this cell](https://docs.google.com/spreadsheets/d/16xRPugw9ubKA1nXHIc5ysVZKokLLhysI-jAu3qbOFJ8/edit#gid=0&range=G6) even if it's a variable, but the req.backend variable is an exception to the rule.

yes, In my investigation, the backend identifier like F_origin_0 was treated as a variable 😅 so I didn't try `req.backend`.

> The 'cleanest' solution might be defining a special REQBACKEND type to describe the unique behaviour, but it would probably be simpler and more maintainable to just hack the identifier checks into the linter phase like I started doing 😅 Does that sound acceptable?

That sounds fine, but we should think if there are other specific type conversion problems (but currently I don't know at the moment). If it might be, we should implement the underlying feature.

And I have one question, what does the `REQBACKEND` type work? I'm guessing when the `BACKEND` type is substituted to `req.backend`, then we'll change its type, but I'd know your thought with a short example 😉 

However, defining `types.REQBACKEND` solution just solves this problem so I could accept your suggestion!
@davinci26 do you have any opinions on this?

2022-08-29 12:16 UTC, davinci26 commented
Works for me, I think `REQBACKEND` is a good tradeoff but we should handle the cast from `BACKEND` to `REQBACKEND`

2022-08-31 08:44 UTC, ivomurrell commented
> And I have one question, what does the `REQBACKEND` type work? I'm guessing when the `BACKEND` type is substituted to `req.backend`, then we'll change its type, but I'd know your thought with a short example 😉

Yes, I think the semantics should look like this:

```vcl
backend F_origin_0 {} // BACKEND
set req.backend = F_origin_0; // implicit cast from BACKEND to REQBACKEND
set req.http.Debug-Fastly-Backend = req.backend; // implicit cast from REQBACKEND to STRING

declare local var.backend BACKEND;
set var.backend = req.backend; // implicit cast from REQBACKEND to BACKEND
set req.http.Debug-Fastly-Backend = var.backend // ERROR: cannot cast a BACKEND to a STRING
```

2022-09-01 14:04 UTC, davinci26 approved these changes
looks great to me, if you can add one test to clarify/document one part that would be great

2022-09-01 14:04 UTC, davinci26 commented on linter/linter.go
>  	case "==", "!=":
can we add a test for that? or a fiddle is this for something like `req.backend == backend_F`?

2022-09-02 14:45 UTC, ysugimoto requested changes
Add one change request.

I'm aware that `BACKEND` type could not use on local variable declaration 🤔 
see: https://fiddle.fastly.dev/fiddle/c8b5dfd6

```
# fiddle says Expected variable type, one of: BOOL, INTEGER, FLOAT, TIME, RTIME, IP or STRING
declare local var.b BACKEND;
```

We should add a type check in the variable declaration, but this is not related to this issue. Let's add another issue and fix it.

2022-09-02 14:45 UTC, ysugimoto commented on types/types.go
> +
This type does not seem to be used in your changes.

2022-09-07 08:53 UTC, ysugimoto approved these changes
Looks good to me 👍  Thank you!

2022-09-07 15:18 UTC, merged